updated

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -13,4 +13,21 @@ ARCHIVE_FILE="${DATE}.tar.gz"
 # Create MySQL dump
 mysqldump --user=${MYSQL_USER} --password="${MYSQL_PASS}" --all-databases > ${BACKUP_FILE}
 
-tar -czvf "${ARCHIVE_FILE}" ${BACKUP_FILE}
+# Check if mysqldump was successful
+if [ $? -eq 0 ]; then
+    echo "MySQL dump created successfully."
+
+    # Compress the dump file
+    tar -czvf "${ARCHIVE_FILE}" ${BACKUP_FILE}
+
+    # Check if compression was successful
+    if [ $? -eq 0 ]; then
+        echo "Backup compressed into archive: ${ARCHIVE_FILE}"
+    else
+        echo "Error compressing the backup file."
+        exit 2
+    fi
+else
+    echo "Error creating MySQL dump."
+    exit 3
+fi
